### ISSUE TITLE
extra pass over db column types

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-indexer#223]
unconflicting things merged recently that were drafted before the db constraints rennovation

**Comment by mitjat** [comment]
I see only two more plan NUMERIC columns, and one of them (emerald ERC-20 balance) needs to not be UINT_NUMERIC anyway, at least until we start processing emerald from round 0 to avoid negative balances.

Closing because it's such a miniscule ticket; we'll do it in the passing, and if we don't, so it goes.
