### ISSUE TITLE
stats/active_accounts query param issue

### ISSUE THREAD

**Issue by buberdds** [oasisprotocol/oasis-indexer#350]
##### SUMMARY
Query param responsible for the size of the step between returned statistic windows not working 

##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE
there's `window_step_seconds` param
`https://index-staging.oasislabs.com/v1/emerald/stats/active_accounts?limit=10&window_step_seconds=300`

##### ACTUAL RESULTS
response ignores `window_step_seconds` and returns default `window_size_seconds`. Looks like some naming mismatch (size vs step)
`{"window_size_seconds":86400,"windows":[{"active_accounts":4137,"window_end":"2022-04-26T20:05:00Z"}]}`

##### EXPECTED RESULTS
`{"window_size_seconds":300,"windows":[{"active_accounts":4137,"window_end":"2022-04-26T20:05:00Z"}]}`

**Comment by buberdds** [comment]
I think I was wrong.  Data granularity looks Ok

`https://index-staging.oasislabs.com/v1/emerald/stats/active_accounts?limit=10&window_step_seconds=300`
```
{"window_size_seconds":86400,"windows":[{"active_accounts":4137,"window_end":"2022-04-26T20:05:00Z"},{"active_accounts":4144,"window_end":"2022-04-26T20:00:00Z"},{"active_accounts":4154,"window_end":"2022-04-26T19:55:00Z"},{"active_accounts":4153,"window_end":"2022-04-26T19:50:00Z"},{"active_accounts":4157,"window_end":"2022-04-26T19:45:00Z"},{"active_accounts":4163,"window_end":"2022-04-26T19:40:00Z"},{"active_accounts":4172,"window_end":"2022-04-26T19:35:00Z"},{"active_accounts":4173,"window_end":"2022-04-26T19:30:00Z"},{"active_accounts":4177,"window_end":"2022-04-26T19:25:00Z"},{"active_accounts":4182,"window_end":"2022-04-26T19:20:00Z"}]}
```

`https://index-staging.oasislabs.com/v1/emerald/stats/active_accounts?limit=10&window_step_seconds=86400`

```
{"window_size_seconds":86400,"windows":[{"active_accounts":3728,"window_end":"2022-04-26T00:00:00Z"},{"active_accounts":3683,"window_end":"2022-04-25T00:00:00Z"},{"active_accounts":3476,"window_end":"2022-04-24T00:00:00Z"},{"active_accounts":3398,"window_end":"2022-04-23T00:00:00Z"},{"active_accounts":3601,"window_end":"2022-04-22T00:00:00Z"},{"active_accounts":3735,"window_end":"2022-04-21T00:00:00Z"},{"active_accounts":3712,"window_end":"2022-04-20T00:00:00Z"},{"active_accounts":3909,"window_end":"2022-04-19T00:00:00Z"},{"active_accounts":3701,"window_end":"2022-04-18T00:00:00Z"},{"active_accounts":3767,"window_end":"2022-04-17T00:00:00Z"}]}
```

**Comment by ptrus** [comment]
Hey, this is actually working as expected, but the documentation might not be clear. (maybe the existence of the `window_size_seconds` field in the response is confusing as well, we though whether we should include it or not - since it will always return `86400` at the moment).

The `active_accounts` always returns 24-hour long windows (no way to control this from the client). With `window_step_seconds` you can control the data granularity (step between windows returned). In the 5-minute case, you get overlapping sliding windows, while in the case of 24-hour step size you get non-overlapping results.

Each window always represents the number of active accounts in the 24-hour (`window_size_secobnds`) period ending at `"window_end"`.

**Comment by buberdds** [comment]
Thank you 🖖
