### ISSUE TITLE
Get delegators list to a validator

### ISSUE THREAD

**Issue by heindrick17** [oasisprotocol/oasis-indexer#391]
I want to get delegators list to a validator.

There isn't such api to get delegators list from validator address.

**Comment by mitjat** [comment]
API note: Since the list of delegators can be potentially very long, it's probably better to implement this as a new endpoint `/consensus/validators/{entity_id}/delegators`, rather than a field in the response to `/consensus/validators/{entity_id}`. This way, the list of delegators can be paginated.
