### ISSUE TITLE
production: Add grafana charts

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/oasis-indexer#83]
##### ISSUE TYPE
- Feature Idea

**Comment by mitjat** [comment]
This was implemented, but was not entirely working due to some typos etc.

Charts are now largely fixed in prod but still needs to be transplanted to staging. Writeup follows.

I also added a graph for DB latencies, and visually spruced up the existing graphs (better labels, units, ordering, etc).

## Debugging prometheus metrics for indexer

Status: [Grafana for production indexer](https://grafana.ops.oasiscloud.io/d/hOGPhb6nk/oasis-indexer-production?orgId=1&from=now-2d&to=now) shows no data
Example query from grafana: `increase(api_v1_request_latencies_sum{service="oasis-indexer"}[$__rate_interval])/increase(api_v1_request_latencies_count{service="oasis-indexer"}[$__rate_interval])`

---
Find metrics exposed by prod indexer. From ops-shell:
```
use_kube_env gcp/production/us-west2
kubectl -n mainnet get services
# ^ output: mainnet-oasis-indexer                      ClusterIP   10.32.187.223   <none>        8008/TCP,8010/TCP,8009/TCP
```
From the [service config](https://github.com/oasislabs/private-charts/blob/master/charts/oasis-indexer/templates/service.yaml#L2) and [default values](https://github.com/oasislabs/private-charts/blob/master/charts/oasis-indexer/values.yaml#L48), we see that :8010 serves prometheus metrics for the API server, and :8009 for the actual indexer/analyzer. 
Let's dig into API because that's what the sample grafana query from above needs. In ops shell:
```
kubectl -n mainnet port-forward --address 0.0.0.0 service/mainnet-oasis-indexer 8010 >>/tmp/8010 &
curl localhost:8010/metrics | tee /tmp/indexer-metrics
```

We can now see the exported metrics in `/tmp/indexer-metrics`. It does have `api_v1_request_latencies_sum` and `api_v1_request_latencies_count`, with _lots_ of labels. *TODO: Restrict label cardinality*

---
Re-check grafana config. Fix errors:
- the prometheus server was the staging one
- the service name in the query was misspelled (should be `mainnet-oasis-indexer`)
- sum-by syntax was wrong; `by` comes last
- request latencies expression fixed. computes only avg latency. *TODO: collect histograms, adapt grafana query to show p99, p95, p90, p50*

**Comment by aefhm** [comment]
Thanks! Nit, the production API request latency [panel](https://grafana.ops.oasiscloud.io/d/hOGPhb6nk/oasis-indexer-production?viewPanel=6&orgId=1&from=now-2d&to=now) looks empty.
